### PR TITLE
Fix EXH for iOS8

### PR DESCRIPTION
**Pull request by carry0987**

### CODE REVIEW

**Comment by DDVD233** [comment]
Version 3.x should still support iOS 8. It is probably a better idea to develop on 3.0_develop branch instead.

By the way, I believe v3 has already solved the problem you described.

**Comment by carry0987** [comment]
> Version 3.x should still support iOS 8. It is probably a better idea to develop on 3.0_develop branch instead.
> 
> By the way, I believe v3 has already solved the problem you described.

But the README file says only support iOS9.0 or higher version

**Comment by DDVD233** [comment]
By far, the deployment target of this app is still iOS 8.0, meaning that you should be able to run the app on an iOS 8 device. However, I don't have any devices/simulators running iOS 8.0 so I'm not sure whether there is any compatibility issue (but you can always test).

**Comment by DaidoujiChen** [comment]
Hello @zjdavid,

我記憶中 3.x 需要 9.0 以上應該是因為 xib 裡面會用到 safe area 的關係
所以 @carry0987 是把 code 推到 2.x 的 branch 裡面

這部分我大概看過之後就會 mer 他進去
感謝

**Comment by DaidoujiChen** [comment]
mer 下去囉 OwOb

**Comment by DaidoujiChen** [comment]
https://dai-hentai-ipa.s3-ap-northeast-1.amazonaws.com/bitrise/2.66_2.66/e-Hentai.ipa

**Pull request merged**
